package model;
// Generated 27-may-2015 14:57:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetalleLeccion generated by hbm2java
 */
@Entity
@Table(name="detalle_leccion"
    ,catalog="tesis"
)
public class DetalleLeccion  implements java.io.Serializable {


     private Integer iddetalleLeccion;
     private Integer numeroPregunta;
     private String pregunta;
     private String respuesta;
     private String mensaje;
     private String observacion;
     private Integer puntuacion;
     private Set leccions = new HashSet(0);

    public DetalleLeccion() {
    }

    public DetalleLeccion(Integer numeroPregunta, String pregunta, String respuesta, String mensaje, String observacion, Integer puntuacion, Set leccions) {
       this.numeroPregunta = numeroPregunta;
       this.pregunta = pregunta;
       this.respuesta = respuesta;
       this.mensaje = mensaje;
       this.observacion = observacion;
       this.puntuacion = puntuacion;
       this.leccions = leccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddetalle_leccion", unique=true, nullable=false)
    public Integer getIddetalleLeccion() {
        return this.iddetalleLeccion;
    }
    
    public void setIddetalleLeccion(Integer iddetalleLeccion) {
        this.iddetalleLeccion = iddetalleLeccion;
    }

    
    @Column(name="numero_pregunta")
    public Integer getNumeroPregunta() {
        return this.numeroPregunta;
    }
    
    public void setNumeroPregunta(Integer numeroPregunta) {
        this.numeroPregunta = numeroPregunta;
    }

    
    @Column(name="pregunta", length=45)
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }

    
    @Column(name="respuesta", length=45)
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }

    
    @Column(name="mensaje", length=45)
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    
    @Column(name="observacion", length=45)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="puntuacion")
    public Integer getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(Integer puntuacion) {
        this.puntuacion = puntuacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detalleLeccion")
    public Set getLeccions() {
        return this.leccions;
    }
    
    public void setLeccions(Set leccions) {
        this.leccions = leccions;
    }




}


