package modelo;
// Generated 04-jun-2015 9:45:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Leccion generated by hbm2java
 */
@Entity
@Table(name="leccion"
    ,catalog="tesis"
)
public class Leccion  implements java.io.Serializable {


     private Integer idleccion;
     private DetalleLeccion detalleLeccion;
     private String estado;
     private String descripcion;
     private Integer puntuacion;
     private Set nivels = new HashSet(0);

    public Leccion() {
    }

	
    public Leccion(DetalleLeccion detalleLeccion) {
        this.detalleLeccion = detalleLeccion;
    }
    public Leccion(DetalleLeccion detalleLeccion, String estado, String descripcion, Integer puntuacion, Set nivels) {
       this.detalleLeccion = detalleLeccion;
       this.estado = estado;
       this.descripcion = descripcion;
       this.puntuacion = puntuacion;
       this.nivels = nivels;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idleccion", unique=true, nullable=false)
    public Integer getIdleccion() {
        return this.idleccion;
    }
    
    public void setIdleccion(Integer idleccion) {
        this.idleccion = idleccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="detalle_leccion_iddetalle_leccion", nullable=false)
    public DetalleLeccion getDetalleLeccion() {
        return this.detalleLeccion;
    }
    
    public void setDetalleLeccion(DetalleLeccion detalleLeccion) {
        this.detalleLeccion = detalleLeccion;
    }

    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="puntuacion")
    public Integer getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(Integer puntuacion) {
        this.puntuacion = puntuacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="leccion")
    public Set getNivels() {
        return this.nivels;
    }
    
    public void setNivels(Set nivels) {
        this.nivels = nivels;
    }




}


